# see http://goreleaser.com

project_name: kubectl-tmplt

before:
  hooks:
    - go mod download
    - make install-tools generate

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/plugin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - replacements:
      386: i386
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
