// Code generated by "stringer -type=instrType"; DO NOT EDIT.

package tool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InstrApply-0]
	_ = x[InstrWait-1]
}

const _instrType_name = "InstrApplyInstrWait"

var _instrType_index = [...]uint8{0, 10, 19}

func (i instrType) String() string {
	if i < 0 || i >= instrType(len(_instrType_index)-1) {
		return "instrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _instrType_name[_instrType_index[i]:_instrType_index[i+1]]
}
